[tools]

# Runtimes
node = "lts"
python = "latest"
go = "latest"
rust = "latest"

# AWS
aws-cli = "latest"
aws-vault = "latest"
terraform = "latest"
terragrunt = "latest"

# Containers
rancher = "latest"

# Package managers
pnpm = "latest"
uv = "latest"
yarn = "latest"
zig = "latest"
bun = "latest"

[tools.claude-code]
version = "latest"
minimum_release_age = "0s"

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
