#!/usr/bin/env bash
set -e
set -u
set -o pipefail

function _install() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "We are on a Mac"
    if ! command -v brew >/dev/null 2>&1; then
      echo "Brew not installed"
    else
      echo "Brew is installed"
      brew install $1
    fi
  else
    echo "We are on Linux I guess..."
  fi
}

_install $1

stow -d ~/dotfiles -vv $1
