return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "css-lsp",
      "dockerfile-language-server",
      "emmet-language-server",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "prettier",
      "prettierd",
      "shfmt",
      "stylelint-lsp",
      "stylua",
      "taplo",
      "terraform-ls",
      "vtsls",
      "yaml-language-server",
    },
  },
}
