#!/usr/bin/env bash
source "$HOME/dotfiles/_install/utils.sh"

# Stow Claude config (~/.claude/{settings.json,CLAUDE.md,skills}) plus the
# claude CLI shell completions.
#
# Note: CLAUDE.md is generated by `codegraph install` between its
# CODEGRAPH_START/END markers — edit it there, not by hand.
stow_pkg "agents"

# Register global (user-scope) MCP servers.
#
# These live in ~/.claude.json, which interleaves config with session state and
# OAuth identity, so it can't be stowed. Re-registering here keeps this repo as
# the source of truth instead.
#
# Declarative on purpose: remove-then-add, so edits to a definition below
# actually take effect rather than being skipped as "already present".
#
# Only a *reference* to the token is committed; the value stays in the
# environment (see CODACY_API_KEY), never in a tracked file.
if command -v claude >/dev/null 2>&1; then
  claude mcp remove codacy -s user >/dev/null 2>&1 || true
  claude mcp add codacy --scope user \
    -e 'CODACY_ACCOUNT_TOKEN=${CODACY_API_KEY}' \
    -- npx -y @codacy/codacy-mcp@latest

  if [ -z "${CODACY_API_KEY:-}" ]; then
    echo "  note: CODACY_API_KEY is unset - Claude Code will warn until it is"
  fi
fi
