import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "screen-256color"

[font]
normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
size = 14
offset = { x = 0, y = 2 }

