import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "screen-256color"

[window]
option_as_alt = "OnlyLeft" # other values are None, OnlyRight, Both

[font]
normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
size = 14
offset = { x = 0, y = 2 }

[selection]
save_to_clipboard = true
